"use client";
import {useEffect,useRef,useState} from "react";

const skills = ["Playwright","Selenium","Postman","JMeter","JavaScript","Java","Jenkins","GitHub Actions"];
const projects = [
  ["01","Playwright Automation Framework","Maintainable UI tests using Page Objects, reusable fixtures, and reliable assertions.","Playwright · Java · JUnit","24 tests passed"],
  ["02","Data-Driven Web Testing","Selenium coverage powered by CSV and Excel datasets, including edge cases and failure evidence.","Selenium · JavaScript · Mocha","20 scenarios covered"],
  ["03","Snapcart CI Pipeline","An automated workflow connecting tests, reports, containers, and deployment checks.","Jenkins · Docker · CI/CD","Pipeline healthy"],
];
function Dots(){return <span className="dots"><i/><i/><i/></span>}
export default function Home(){
 const terminalRef=useRef<HTMLDivElement>(null);
 const [terminalActive,setTerminalActive]=useState(false);
 useEffect(()=>{const node=terminalRef.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setTerminalActive(true);observer.disconnect()}},{threshold:.3});observer.observe(node);return()=>observer.disconnect()},[]);
 return <main>
  <nav className="nav shell"><a className="logo" href="#top" aria-label="Anna — back to top">A<span>✦</span></a><div className="navlinks"><a href="#about">About</a><a href="#work">Work</a><a href="#contact">Contact</a></div><a className="pill" href="#contact">Let&apos;s talk ↗</a></nav>
  <section className="hero shell" id="top">
   <div><p className="eyebrow"><b/> Open to creative web & QA opportunities</p><h1>I design, build,<br/>test, and <em>improve</em><br/>digital experiences.</h1><p className="intro">Creative web maker and QA Engineer based in Vancouver, blending a user-first eye with thoughtful design, front-end building, and reliable testing.</p><div className="actions"><a className="button" href="#work">Explore my work ↓</a><a className="link" href="https://github.com/sureeporn-sudo">GitHub ↗</a></div></div>
   <div className="workspace">
    <div className="code"><header><Dots/><span>anna.spec.js</span><small>⌘ K</small></header><pre><span>describe</span>(<b>&apos;great experiences&apos;</b>, () =&gt; {"{"}{"\n"}  <span>it</span>(<b>&apos;should feel effortless&apos;</b>, () =&gt; {"{"}{"\n"}    expect(product).toBe(<i>reliable</i>);{"\n"}  {"}"});{"\n"}{"}"});</pre></div>
    <div className="profile"><div className="portrait"><small>ANNA.JPG</small><img src="/anna-profile.png" alt="Anna Sureeporn Apaikawee, QA Engineer"/></div><div><small>QA ENGINEER</small><b>Sureeporn<br/>Apaikawee</b><span>Vancouver, BC</span></div></div>
    <div className="tests"><div><Dots/><b>Test run</b></div><p>✓ Login flow</p><p>✓ Add to cart</p><p>✓ API response</p><footer><span>3 passed</span><small>1.8s</small></footer></div><div className="badge">ship it! ↗</div>
   </div>
  </section>
  <div className="marquee"><div className="marqueetrack"><span className="marqueegroup">UX/UI DESIGN <i>✦</i> CREATIVE WEB <i>✦</i> FRONT-END <i>✦</i> QUALITY ASSURANCE <i>✦</i> INTERACTION DESIGN <i>✦</i></span><span className="marqueegroup" aria-hidden="true">UX/UI DESIGN <i>✦</i> CREATIVE WEB <i>✦</i> FRONT-END <i>✦</i> QUALITY ASSURANCE <i>✦</i> INTERACTION DESIGN <i>✦</i></span></div></div>
  <section className="about shell section" id="about"><Label n="01" text="ABOUT.EXE"/><div className="aboutgrid"><h2>Curious by nature.<br/><em>Quality-focused</em><br/>by practice.</h2><div className="copy"><p>I&apos;m Anna, a Software Quality Assurance Engineering student who enjoys finding the small details that make a big difference.</p><p>My background in digital marketing gives me a user-first perspective; my testing toolkit helps me turn that perspective into clear, actionable results.</p><div className="location"><div className="locator" aria-hidden="true"><i/><i/><b/></div><span><small>CURRENTLY BASED IN</small><b>Vancouver, BC</b></span></div></div></div></section>
  <section className="shell toolkit"><div ref={terminalRef} className={"terminal terminalsequence "+(terminalActive?"is-running":"")}><header><Dots/><span>anna@portfolio — toolkit</span><small>⌁</small></header><div className="terminalbody"><p className="commandline"><b>anna@creative ~ %</b> <span>run toolkit --all</span></p><p className="muted loadingline">Loading Anna&apos;s creative toolkit<span className="loadingdots"><i>.</i><i>.</i><i>.</i></span></p><div className="skills">{skills.map((s,i)=><div className="skillitem" style={{"--delay":`${2.15+i*.18}s`} as React.CSSProperties} key={s}><span>✓</span> {s}<small>0{i+1}</small></div>)}</div><p className="success readyline">8 tools ready · let&apos;s build meaningful experiences<span className="cursor">_</span></p></div></div></section>
  <section className="work shell section" id="work"><Label n="02" text="SELECTED_WORK"/><div className="workhead"><h2>Things I&apos;ve<br/><em>designed & built.</em></h2><p>A mix of playful web experiences and quality-focused engineering—where visual ideas meet thoughtful execution.</p></div>
   <article className="featured">
    <div className="featuredcopy"><div className="featuretop"><span>FEATURED INTERACTIVE PROJECT</span><i>NEW ✦</i></div><h3>Valentine<br/><em>Letter</em></h3><p>A playful web experience made to feel personal, charming, and fun to explore. This project reflects the direction I love most: combining visual design, interaction, and code to create something people can actually enjoy.</p><div className="featuremeta"><span>UX/UI</span><span>Creative coding</span><span>Interactive web</span></div><div className="featureactions"><a className="play" href="https://sureeporn-sudo.github.io/ValentineLetter/" target="_blank" rel="noreferrer">Play live <b>↗</b></a><a href="https://github.com/sureeporn-sudo/ValentineLetter" target="_blank" rel="noreferrer">View code ↗</a></div></div>
    <div className="browsercard"><header><Dots/><span>sureeporn-sudo.github.io/ValentineLetter</span><b>♡</b></header><div className="livepreview"><iframe src="https://sureeporn-sudo.github.io/ValentineLetter/" title="Live preview of Anna's Valentine Letter interactive website" loading="lazy"/><a href="https://sureeporn-sudo.github.io/ValentineLetter/" target="_blank" rel="noreferrer" aria-label="Open Valentine Letter interactive website"><span>CLICK TO PLAY</span><b>↗</b></a></div><small>Made with a little code & a lot of heart.</small></div>
   </article>
   <div className="projectlist">{projects.map(p=><article className="project" key={p[0]}><small>PROJECT / {p[0]}</small><div><h3>{p[1]}</h3><p>{p[2]}</p><span className="tags">{p[3]}</span></div><div className="status"><span>● {p[4]}</span><a href="https://github.com/sureeporn-sudo" aria-label={"View "+p[1]}>↗</a></div></article>)}</div></section>
  <section className="contact section" id="contact"><div className="shell contactgrid"><div><Label n="03" text="CONTACT.TXT"/><h2>Have a project,<br/>an opportunity, or<br/><em>a curious idea?</em></h2></div><div className="contactcard"><small>MY INBOX IS OPEN</small><p>Let&apos;s talk about quality, creative technology, or how I could help your team.</p><a href="mailto:sureeporn.apaikawee@gmail.com"><span>sureeporn.apaikawee@gmail.com</span><span>↗</span></a><div><a href="https://github.com/sureeporn-sudo" target="_blank" rel="noreferrer">GitHub</a> • <a href="https://www.linkedin.com/in/sureeporn-apaikawee-8184571b0/" target="_blank" rel="noreferrer">LinkedIn</a></div></div></div></section>
  <footer><div className="shell"><p>Designed with curiosity. Tested with care.</p><p>© 2026 ANNA — QA ENGINEER</p><a href="#top">Back to top ↑</a></div></footer>
 </main>
}
function Label({n,text}:{n:string,text:string}){return <div className="label"><span>{n}</span>{text}</div>}
